server:
  port: 30000
spring:
  application:
    name: sub-unified-gateway
  cloud:
    #网关配置
    gateway:
      routes: # 网关路由配置
        - id: sub-service-center # 路由id，自定义，只要唯一即可
          # uri: http://127.0.0.1:8081 # 路由的目标地址 http就是固定地址
          uri: lb://sub-service-center # 路由的目标地址 lb就是负载均衡，后面跟服务名称
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/service-center/** # 这个是按照路径匹配，只要以/service-cetner/开头就符合要求
      # 全局的跨域处理
      globalcors:
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://localhost:30000"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期
eureka:
  client:
    #eureka-服务端地址，多节点,隔开
    service-url:
      defaultZone: http://admin:123456@127.0.0.1:30080/eureka
    # 是否注册到 Eureka
    register-with-eureka: true
    # 是否拉取服务列表
    fetch-registry: true
    # 拉取服务列表间隔
    registry-fetch-interval-seconds: 30
  instance:
    # 优先使用 IP 注册
    prefer-ip-address: true
    # 自定义实例 ID 显示
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    # 心跳间隔
    lease-renewal-interval-in-seconds: 30
    # 续约到期时间
    lease-expiration-duration-in-seconds: 90